extends: ['airbnb-base', 'prettier']
parserOptions:
    ecmaVersion: 2020
env:
    jest: true
plugins: ['prettier']
rules:
    class-methods-use-this: 0
    no-plusplus: 0
    import/extensions: [2, 'ignorePackages']
