FROM node:16 as build
WORKDIR /srv/package

COPY ../../ ./
RUN ls
RUN cd ./services/kareoke
RUN npm ci

FROM node:16
USER node

COPY --from=build ./node_modules /srv/package/servinode_modules

CMD npm run start
